spring:
  data:
    mongodb:
      uri: ${MONGO_URI_CLOUD:mongodb://localhost:27017}
      database: ${DB_NAME:nest_base}
  mail:
    host: smtp.mail.ru
    port: 465
    username: ${MAIL_USERNAME:zurix@mail.ru}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

server:
  port: ${PORT:3000}

app:
  jwt:
    access-secret: ${ACCESS_JWT_SECRET:defaultAccessSecretKeyThatIsLongEnough}
    refresh-secret: ${REFRESH_JWT_SECRET:defaultRefreshSecretKeyThatIsLongEnough}
    access-expiration: 600000
    refresh-expiration: 36000000

springdoc:
  swagger-ui:
    path: /swagger-doc
